### ISSUE TITLE
sampler tests

### ISSUE THREAD

**Issue by jeremiecoullon** [rlouf/mcx#59]
It might be nice to add some more rigorous tests to the sampler (though the mean and variance tests at the moment are good!).

For example the Kernel goodness of fit test ([here](https://arxiv.org/abs/1602.02964) or [here](https://arxiv.org/abs/1602.03253)).

This is obviously not urgent, I just thought it might be a nice thing. I don't know how Stan and other packages do integrations tests for their samplers; perhaps they also test the first few moments of the samples?

**Comment by rlouf** [comment]
I totally agree! Rainier has an interesting approach to testing inference by using Simulation Based Calibration:

https://github.com/stripe/rainier/blob/develop/rainier-test/src/main/scala/com/stripe/rainier/core/SBCModel.scala

Which I quite like. What do you think?

**Comment by jeremiecoullon** [comment]
Nice! Is [this](https://arxiv.org/abs/1804.06788) that technique? 
I've come accross a similar method; but my supervisor called it the [prior reproduction test](https://www.jeremiecoullon.com/2020/02/04/priorreproductiontest/)

**Comment by rlouf** [comment]
Yes, that's the article. That's essentially what you write about in your blog post except that instead of comparing distributions directly you compare the rank statistic to the uniform distribution.

By the way, I don't know if you saw on Twitter, but we're discussing with PyMC3 and Numpyro devs to move the inference code in a separate repository. It will have essentially MCX's code structure + numpyro's NUTS implementation at the beginning. Tests based on simulation-based calibration would be a great addition.

**Comment by jeremiecoullon** [comment]
Seperating the inference from the other stuff sounds like a good idea!
I'll have a closer look at [SMC](https://arxiv.org/abs/1804.06788) at some point; it would be good to add this.

**Comment by rlouf** [comment]
Yes, and it shouldn't be that computationally challenging using JAX.

**Comment by rlouf** [comment]
@jeremiecoullon Development of inference algortihms will be moved in the short-term to [BlackJAX](https://github.com/blackjax-devs/blackjax). The library is developed in collaboration with the PyMC and Numpyro teams. We could use your help to develop more robust tests for sampling algorithms!
